{
 "title": "AI智算-GPU资源监控概览-20241127",
 "description": "适用于AI智算场景中监控NVIDIA GPU资源概览,依赖组件: dcgm-exporter:3.3.0-3.2.0-ubuntu22.04、prometheus:v2.39.1、grafana:10.3.3",
 "tags": [
  "A100",
  "A800",
  "H100",
  "智算中心",
  "NVIDIA",
  "GPU",
  "kason"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "idc", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_TEMP,Hostname)"
    }
   },
   {
    "name": "interval",
    "label": "间隔时间",
    "query": "1m,10m,30m,1h,6h,12h,1d,2d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(DCGM_FI_DEV_GPU_UTIL,exported_namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU资源监控概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU卡使用情况",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"})",
     "legendFormat": "总GPU卡"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",Hostname=~\"$hostname\"})",
     "legendFormat": "已申请GPU卡"
    },
    {
     "expr": "count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"}[1m])>0)",
     "legendFormat": "已使用GPU卡"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",Hostname=~\"$hostname\"})-count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"}[1m])>0)",
     "legendFormat": "未使用GPU卡"
    }
   ]
  },
  {
   "title": "NVIDIA H100 80GB HBM3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{modelName=\"NVIDIA H100 80GB HBM3\",Hostname=~\"$hostname\"})",
     "legendFormat": "total"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",modelName=\"NVIDIA H100 80GB HBM3\",Hostname=~\"$hostname\"})",
     "legendFormat": "request"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{pod!=\"\",modelName=\"NVIDIA H100 80GB HBM3\",Hostname=~\"$hostname\"} > 0)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "NVIDIA A800-SXM4-80GB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{modelName=\"NVIDIA A800-SXM4-80GB\",Hostname=~\"$hostname\"})",
     "legendFormat": "total"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",modelName=\"NVIDIA A800-SXM4-80GB\",Hostname=~\"$hostname\"})",
     "legendFormat": "request"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{pod!=\"\",modelName=\"NVIDIA A800-SXM4-80GB\",Hostname=~\"$hostname\"} > 0)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "NVIDIA A100-SXM4-80GB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{modelName=\"NVIDIA A100-SXM4-80GB\",Hostname=~\"$hostname\"})",
     "legendFormat": "total"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",modelName=\"NVIDIA A100-SXM4-80GB\",Hostname=~\"$hostname\"})",
     "legendFormat": "request"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{pod!=\"\",modelName=\"NVIDIA A100-SXM4-80GB\",Hostname=~\"$hostname\"} > 0)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "GPU 平均温度",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_TEMP{Hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU使用总功率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(DCGM_FI_DEV_POWER_USAGE{Hostname=~\"$hostname\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "总GPU利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"}[3m])>0) / count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",Hostname=~\"$hostname\"}) * avg(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "已使用GPU利用率",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU算力卡健康状态&版本信息概览",
   "type": "table",
   "description": "监控展示NVIDIA驱动版本、芯片类型、GPU卡健康状态等",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"}) by (Hostname)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (Hostname,modelName,host_ip,DCGM_FI_DRIVER_VERSION) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info)",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(kube_node_info{node=~\"$hostname\"},\"Hostname\",\"$1\",\"node\",\"(.*)\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(sum by (node) (irate(container_cpu_usage_seconds_total{container!=\"\",node=~\"$hostname\"}[2m]))  / sum by (node) (kube_node_status_allocatable{resource=\"cpu\", unit=\"core\", node=~\"$hostname\"}),\"Hostname\",\"$1\",\"node\",\"(.*)\")",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "label_replace(sum by (node) (container_memory_working_set_bytes{container!=\"\",node=~\"$hostname\"}) / sum by (node) (kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"$hostname\"}),\"Hostname\",\"$1\",\"node\",\"(.*)\")",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "avg by (Hostname) (DCGM_FI_DEV_MEM_CLOCK{Hostname=~\"$hostname\"}*1000000)",
     "legendFormat": "内存时钟频率"
    },
    {
     "expr": "avg by (Hostname) (DCGM_FI_DEV_SM_CLOCK{Hostname=~\"$hostname\"}*1000000)",
     "legendFormat": "SM 时钟频率"
    }
   ]
  },
  {
   "title": "GPU利用率",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (Hostname,host_ip) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info) ",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "主机已申请GPU卡明细（节点级别）",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} * on (pod) group_left(host_ip) kube_pod_info) by (Hostname,host_ip)",
     "legendFormat": "总GPU资源"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",Hostname=~\"$hostname\"}) by (Hostname)",
     "legendFormat": "已申请GPU资源"
    },
    {
     "expr": "count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"}[1m])>0) by (Hostname)",
     "legendFormat": "已使用GPU资源"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",Hostname=~\"$hostname\",exported_namespace=~\"fdu-project\"}) by (Hostname)",
     "legendFormat": "已申请GPU资源（外部业务）"
    },
    {
     "expr": "count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",Hostname=~\"$hostname\",exported_namespace=~\"fdu-project\"}[1m])>0) by (Hostname)",
     "legendFormat": "已使用GPU资源（外部业务）"
    },
    {
     "expr": "count(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",Hostname=~\"$hostname\",exported_namespace!~\"fdu-project\"}) by (Hostname)",
     "legendFormat": "已申请GPU资源（内部业务）"
    },
    {
     "expr": "count(avg_over_time(DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",Hostname=~\"$hostname\",exported_namespace!~\"fdu-project\"}[1m])>0) by (Hostname)",
     "legendFormat": "已使用GPU资源（内部业务）"
    }
   ]
  },
  {
   "title": "GPU总使用率趋势图",
   "type": "timeseries",
   "description": "单台、多台汇总展示",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"})",
     "legendFormat": "GPU使用率"
    }
   ]
  },
  {
   "title": "GPU资源使用率明细（监控到Pod细粒度）",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{exported_pod!=\"\",Hostname=~\"$hostname\",exported_namespace=~\"$namespace\"} * on (pod) group_left(host_ip) kube_pod_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "(DCGM_FI_DEV_FB_USED{exported_pod!=\"\",Hostname=~\"$hostname\",exported_namespace=~\"$namespace\"}/(DCGM_FI_DEV_FB_USED{exported_pod!=\"\",Hostname=~\"$hostname\",exported_namespace=~\"$namespace\"}+DCGM_FI_DEV_FB_FREE{exported_pod!=\"\",Hostname=~\"$hostname\",exported_namespace=~\"$namespace\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU利用率（单台展示）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (Hostname,host_ip) (DCGM_FI_DEV_GPU_UTIL{Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info) ",
     "legendFormat": "{{host_ip}}"
    }
   ]
  },
  {
   "title": "GPU显存使用率（单台展示）",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(DCGM_FI_DEV_FB_USED{pod!=\"\",Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info) by (Hostname,host_ip))/(sum(DCGM_FI_DEV_FB_USED{Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info) by (Hostname,host_ip)+sum(DCGM_FI_DEV_FB_FREE{Hostname=~\"$hostname\"} * on (pod) group_left (host_ip) kube_pod_info) by (Hostname,host_ip)) * 100",
     "legendFormat": "{{host_ip}}"
    }
   ]
  }
 ]
}